### ISSUE TITLE
gtk3 avoidStruts troubles and tray not refreshing

### ISSUE THREAD

**Issue by kpbochenek** [travitch/taffybar#255] opened 2018-03-18 01:03 UTC
Hi,

when updating to gtk3 version taffybar stopped having dedicated space at the top of my screen and other windows started showing below or above it.

My .xmonad configuration is just: `layoutHook = avoidStruts $ ( my layouts definition here)`

Another thing is default configuration which changed to css no longer resembles the one from screenshot in README.

Third thing is icons in tray don't refresh :/

**Comment by kpbochenek** [comment] 2018-03-18 01:10
Also pressing on application title in taffybar opened menu of active applications, currently it is unreadable :/

**Comment by IvanMalison** [comment] 2018-03-18 01:41
You need to run the docks command on your configuration as well.

import           XMonad.Hooks.ManageDocks

> Third thing is icons in tray don't refresh :/

You mean the systray? What do you mean they don't refresh.

I am currently working on #109 which will add support for a new, better tray.

> is unreadable :/

Is it unreadable because of the theme settings, perhaps?

**Comment by kpbochenek** [comment] 2018-03-18 01:41
![2018-03-18-023852_608x143_scrot](https://user-images.githubusercontent.com/10478402/37561697-8addbb04-2a55-11e8-9be2-dfcc5661b840.png)
Okay so avoidStruts works fine, just a taffybar grew up to big size but I forgot I should adjust `barHeight` from configuration.

Other problems still exist, also I have no idea how to scale down icons :/

(removed everything from .css to see if config caused any issues that's why white background, but no luck)

**Comment by kpbochenek** [comment] 2018-03-18 01:46
![2018-03-18-024432_554x201_scrot](https://user-images.githubusercontent.com/10478402/37561734-7793d6b8-2a56-11e8-92a1-8d8fead78055.png)

Color issue with default scheme

**Comment by kpbochenek** [comment] 2018-03-18 01:52
![2018-03-18-024857_317x110_scrot](https://user-images.githubusercontent.com/10478402/37561760-06fc792c-2a57-11e8-967d-d35bb66fc767.png)
When we move windows on taffybar it leaves red lines as this is my color of active window.

Then taffybar refreshes and those lines are gone but not in tray.

here after few minutes lines are still there because tray is not refreshing.
Also I can mute / unmute but sound icon is not changing.

**Comment by IvanMalison** [comment] 2018-03-18 01:52
@kpbochenek Yeah the switcher just needs to be themed.

I don't think anything is set in the css as of right now. Should be pretty easy to fix.

**Comment by IvanMalison** [comment] 2018-03-18 01:54
> Then taffybar refreshes and those lines are gone but not in tray.

Yes, this is a known issue. See #177 . Again #109 is the way forward anyway, since XEMBED is officially deprecated.

**Comment by kpbochenek** [comment] 2018-03-18 01:57
cool, I will take a look.

In meanwhile, how can I fastest find out about styling taffybar?

I found standard gtk3 css guide: https://developer.gnome.org/gtk3/stable/chap-css-overview.html

So I should work out what attributes to add but how to find out about component names?

e.g. `.InnerContainer` `.IconImage`

**Comment by IvanMalison** [comment] 2018-03-18 02:09
You need to find the classes or names that are assigned to the widgets that you want to style.

As far as I know, WorkspaceHUD is the only widget that actually sets gtk3 classes at the moment:

https://github.com/IvanMalison/taffybar/blob/0f57e29821f4d2255af78fec8b762223589dedef/src/System/Taffybar/WorkspaceHUD.hs#L143

Window switcher does seem to set names for some of its widgets:

https://github.com/IvanMalison/taffybar/blob/0f57e29821f4d2255af78fec8b762223589dedef/src/System/Taffybar/WindowSwitcher.hs#L81

 I'm not 100% sure whether or not names can be used for styling things with css

**Comment by IvanMalison** [comment] 2018-03-18 02:20
I don't use the window switcher menu much so I hadn't noticed this issue, but it turns out I also have it.

Was able to fix it by using add class as shown, and then putting:

``` css
.WindowSwitcher * {
	background-color: @bg-color;
}
```

in taffybar.css

**Comment by kpbochenek** [comment] 2018-03-18 02:31
Will try to fix that tomorrow.

Tried to pinpoint a culprit causing taffybar to grow to big size, and it is actually `tray` component.
Without it all is nicely aligned and flat.

Do you think it will be quick to implement a new tray or it might be worth fixing a current one before a new one is implemented?

**Comment by IvanMalison** [comment] 2018-03-18 03:08
> Do you think it will be quick to implement a new tray or it might be worth fixing a current one before a new one is implemented?

I've tried a bunch of stuff to fix those random graphical glitches and I could never really get things working. Whatever the issue is, its not obvious, and it may simply be a that there is a fundamental issue with mixing xembed and gtk. Making a new tray from scratch would be a monumental amount of work and not something I think anyone is interted in, especially because XEMBED is deprecated.

The new approach is compatible with things like wayland, allows for more uniform menu display (with theming and all that good stuff) uses native gtk widgets, and allows us to support a bunch of newer types of system tray widgets.

I should probably be done with the tray relatively soon. Hard to pinpoint an exact time as it depends on how much work I put in to it, but it might be as soon as next week. Probably no later than a month from now. The new tray should also (theoretically) be somewhat backwards compatible through xembedsniproxy.

> Tried to pinpoint a culprit causing taffybar to grow to big size, and it is actually tray component.
> Without it all is nicely aligned and flat.

I don't think it would be hard to fix the size issue that you have.

**Comment by kpbochenek** [comment] 2018-03-19 00:13
from master with adjusted color scheme to resemble stable version:
![2018-03-19-004234_1919x50_scrot](https://user-images.githubusercontent.com/10478402/37572716-8e5a5a48-2b0f-11e8-9277-f97cfe0bd7f7.png)

from branch stable-5.0:
![2018-03-19-003333_1919x122_scrot](https://user-images.githubusercontent.com/10478402/37572717-8e7a4c2c-2b0f-11e8-9d5e-e4a48ba19486.png)

To sum up:
- when clicking on workspaceHUD and active applications menu is expanded background should be dark (probably fixable by what you proposed)
- enormous spacing between workspace names
- no idea how to set green color for application title
- tray causes taffybar height to be increased and scale up everything. Tray icons not refreshing. (could be fixed in future with #109)
- clicking on calendar expands it in a place of date which makes it impossible to close.

Haha found this in #237 :

https://user-images.githubusercontent.com/8163/32417918-4edb72d4-c215-11e7-9d52-7a6bf58f54fe.png

https://user-images.githubusercontent.com/8163/32417922-55e3e9c6-c215-11e7-96f5-7032e75568d3.png

Same as my images :p 

Most of those issues were actually raised there, not sure what is your approach to tracking them as that PR was already merged.

**Comment by IvanMalison** [comment] 2018-03-19 01:09
@kpbochenek are you using workspacehud or workspace switcher?

> enormous spacing between workspace names

Can you post the configuration you are using? There are some configurations that would cause this depending on the number of open windows. It looks to me like you are using workspace switcher based on the fact that you have brackets around 3.

**Comment by kpbochenek** [comment] 2018-03-19 08:19
This is my configuration:
https://pastebin.com/ZrmpVAWt

About calendar, on branch 0.5:
![2018-03-19-091142_226x132_scrot](https://user-images.githubusercontent.com/10478402/37584394-97611596-2b55-11e8-9b0c-013c23afa996.png)
On master:
![2018-03-19-091142_226x132_scrot2](https://user-images.githubusercontent.com/10478402/37584460-d9749002-2b55-11e8-808d-00ffe26a363d.png)
(to close calendar it was enough to click on time/data, but with `master` version it is no longer possible)

Okay I can see example about workspaceHUD I will try to use that.
What is a difference between `taffybarPagerNew` and a `HUD` version?

**Comment by IvanMalison** [comment] 2018-03-28 19:41
> What is a difference between taffybarPagerNew and a HUD version?

The HUD version is actually a completely different widget system that was built from the ground up. There is a legacy function that supports taking all the arguments that the old version took, but it has many more features and is much more actively developed than workspace switcher.

Filed #260 for adding CSS classes, #261 for the calendar popup issue.

**Closed by IvanMalison** 2018-03-28 19:41 UTC
