### ISSUE TITLE
Can you please make Arch Linux package?

### ISSUE THREAD

**Issue by perglr** [travitch/taffybar#151] opened 2016-05-18 10:57 UTC

**Comment by jokogr** [comment] 2016-05-19 18:15
The [ArchHaskell repository](https://wiki.archlinux.org/index.php/ArchHaskell) provides already one, it's the haskell-taffybar package.

**Comment by joshproehl** [comment] 2017-03-07 22:39
It would be nice to have an easily installed package for users who didn't want to install the entire haskell ecosystem. (ArchHaskell is not something I'd recommend to someone who just wanted to try out xmonad and wants a status bar) 
Something along the lines of the aura/aura-bin style packages would be nice if possible.

**Comment by simpers** [comment] 2017-08-15 16:12
Looking for some help with this too. Even some help on how to run it directly from the git repo could help for now. I am in no way experienced with Haskell.

**Comment by IvanMalison** [comment] 2017-08-15 17:26
It's already cabal installable. IMO it doesn't make sense to have an arch linux package.

**Comment by IvanMalison** [comment] 2017-08-15 17:57
> Even some help on how to run it directly from the git repo

Do you have ghc and cabal set up?

what happens when you run cabal install from the repo directory

**Comment by simpers** [comment] 2017-08-15 19:24
It does make complete sense for somebody that doesn't normally need cabal. It pains me evey time when I need to get a new package manager, and seeing as XMonad and all the other components in my system right now that I've put together do fine without cabal, stack or ArchHaskell (which would require me to reinstall all the packages).

So yes, it does make sense to those that don't use these options. I'm always on the verge of dropping XMonad just becuase of the complications with Haskell, but it is the best tiling WM I've used so far, and am sticking with it becuase of that.

So that's my reason, and some simple help to just build it would be appreciated and I could figure out the packaging itself later on.

Meaning, how do I get a binary that I can place in a location I have in my path? or instance, when trying to compile right now I get an error:

```
System/Taffybar/StrutProperties.hs:4:1: error:
    Failed to load interface for ‘Graphics.UI.Gtk’
    Use -v to see a list of the files searched for.
```

even though I installed the required packages (through pacman in Arch, as I don't use the other options.).

So there must be an issue with the linking here. 

So I'm just asking how to compile this, to say a ./bin/, such that I then can package it with a PKGBUILD.

**Comment by jiajunhuang** [comment] 2017-08-23 13:38
Package in official package system is still needed, `ArchHaskell` will break dependency sometimes.

**Comment by LeifW** [comment] 2018-01-24 16:05
Wouldn't this issue be more appropriate to bring up with Arch Linux?
If you want to add a package to Arch Linux, you can add it to AUR yourself, e.g. https://aur.archlinux.org/packages/xmobar-alsa/

If it becomes popular enough, then perhaps a Trusted User will adopt it into the official package repos (e.g. [community]).

**Comment by simpers** [comment] 2018-01-26 06:28
@LeifW Not at all. That was the point. Asking the guy who made it to provide it seems reasonable to me, as AUR is just that, Arch User Repository. And I tried to get the hang of how to do this myself, but the problem is not the package, it is the building of a Haskell package when I have no interest in adding `ArchHaskell` to my Arch repo.

I have too little experience with Haskell to be able to compile it to a binary that can be shipped in a package. And when trying to google they only suggest you add that repo and use a package manager which will do the magic for you, which I don't want to do. So then I'd rather not dive deeper into the Haskell swamp at all :)

**Comment by LeifW** [comment] 2018-01-26 07:04
I could make a PKGBUILD for this to put in AUR, if someone else wanted to maintain it (I don't use taffybar myself).

**Comment by simpers** [comment] 2018-01-26 07:42
That would be very much appreciated! I could try to do so but I cannot promise anything yet as I haven't even been able to try taffybar yet, @LeifW

**Comment by IvanMalison** [comment] 2018-01-27 08:01
@LeifW 
Please do not make an arch package. Haskell is super messed up in arch. taffybar should be installed with cabal or stack.

**Comment by simpers** [comment] 2018-01-27 09:56
@IvanMalison Which is the exact reason I would need one, along with others I'm sure. I don't like third party package managers, and Haskell's are a mess.

**Comment by IvanMalison** [comment] 2018-01-27 12:17
@simpers Read this: https://www.reddit.com/r/archlinux/comments/7hanz7/whats_the_current_state_of_haskell_on_arch/

or

https://wiki.archlinux.org/index.php/Haskell#Problems_with_linking

The consensus there is that making arch packages for haskell programs is pointless.

This is even more true for something like taffybar, which actually works with the compiler etc. and is not merely a binary.

> I don't like third party package managers, and Haskell's are a mess.

They're not perfect, but for what you seem to want to use them for they actually work pretty well. stack in particular can make things pretty easy with taffybar, but suit yourself.

@travitch In the interest of preventing poor user experience. I would suggest that you request that no arch package be created.

**Comment by LeifW** [comment] 2018-01-27 20:35
Here is a PKGBUILD for taffybar on AUR, you can install with `yaourt -S taffybar` (or whatever you prefer to build those things).
https://aur.archlinux.org/packages/taffybar/
If it becomes popular enough, perhaps in can be included in the official [community] binary repo.

You should add a taffybar.hs to $HOME/.connfig/taffybar/, and add the appropriate hooks to your xmonad.hs.
(it seems to work with the xmonad.hs.example and the taffybar.hs.example included in this repo, apart from the bar getting covered up by windows).

Not that this package is dynamically linked against Haskell packages in the [community] repo, and will need to be rebuilt when those are upgraded.

**Comment by LeifW** [comment] 2018-01-27 21:16
Could also do a -git version of this package, to install from this git repo, since the last Hackage release was 2 years ago.

**Comment by simpers** [comment] 2018-01-30 07:29
@IvanMalison and what exactly do I want to use it for? I am merely using XMonad as my WM but the whole Haskell hell is putting me off and I've been thinking of migrating to [neurowm](https://github.com/nnoell/neurowm) instead for that reason. The problem though is having the time to do so.

@LeifW I will have a look at it when I can as I am a bit too busy right now with various other things. Will try it within a week or so, I hope. But cheers!

**Comment by simpers** [comment] 2018-01-30 17:54
@IvanMalison I'll be fair and say that it's been a few years since I last tried, sure, but my experience with any kind of package manager that isn't the default one for the distro is bad. So I always try not to involve a third party package manager. Plus some of them only install for the curreny user, which forces multiple installations. It's just not attractive to me.

I have no issues with the normal packages for XMonad + deps and haven't had. I just have to rebuild the cache or something sometimes, that's all. But the last time I tried to fix it through some package manager it just corrupted all of my deps in the rest of the repositories, e.t.c.

Either case, you're not forced to install it using the AUR so what does it matter to you?

**Comment by simpers** [comment] 2018-01-30 17:56
@LeifW Regarding the git version, would that be much work to fix? That's what I wanted to fix myself but I never managed to figure out how to compile it even (without cabal/stack/whatever) so I never got there.

**Comment by IvanMalison** [comment] 2018-01-30 20:10
> @IvanMalison I'll be fair and say that it's been a few years since I last tried, sure, but my experience with any kind of package manager that isn't the default one for the distro is bad. So I always try not to involve a third party package manager.

stack is not really a package manager, but a build tool. The problem with thinking of xmonad/taffybar as operating system packages is that that's not really what they are, because they aren't simply "a binary/executable piece of code", so much as a framework, around which you build your own WM/status bar. Both taffybar and xmonad absolutely require a full ghc/cabal installation because they are Haskell packages, not operating system packages. The binary that you end up running is one that will be compiled from the code that you write as your config. pacman/whatever aur helper you use just don't really have the tools to properly set everything up for you.

> Plus some of them only install for the current user, which forces multiple installations. It's just not attractive to me.

This issue is extremely easy to overcome: at the end of your build script, simply copy the resulting executable to /usr/lib/bin, and change the permissions...
 
> I have no issues with the normal packages for XMonad + deps and haven't had. I just have to rebuild the cache or something sometimes, that's all. But the last time I tried to fix it through some package manager it just corrupted all of my deps in the rest of the repositories, e.t.c.

Read the links I posted above to understand why this happened.

> Either case, you're not forced to install it using the AUR so what does it matter to you?

Because if there IS an aur package, users like you who are unfamiliar with the haskell ecosystem will almost undoubtedly use it, then get frustrated when upgrades or something else causes it not to work, and ultimately get turned off or switch to something else. Having a PKGBUILD might attract a few more users, but I think that most of them would likely not be retained because the experience will inevitably be subpar.

The only reliable way to get taffybar to install in a way that is upgradeable, resiliant and robust is to use stack or cabal.

There actually might be a way to make a PKGBUILD for taffybar that uses stack (instead of a system level ghc/cabal), and this might be something that could be a good idea.

**Comment by LeifW** [comment] 2018-01-30 21:06
@simpers It's simple enough to adapt from the existing PKGBUILD for taffybar. There's just been some new dependencies added since the last release. I'll put up a taffybar-git on AUR later.

It shouldn't be possible to mess up system-installed packages with user-level tools like cabal-install or stack. If you run `ghc-pkg list`, it should list all your system-installed packages under /usr/lib/ghc-8.2.2/package.conf.d, and cabal-install (run as regular user) installed packages under $HOME/.ghc/x86_64-linux-8.2.2/package.conf.d. The former directory is owned by root, and other tools won't be able to mess with it without `sudo`.

The different ways of installing Haskell packages on Arch are mentioned at https://wiki.archlinux.org/index.php/haskell#Managing_Haskell_packages

I myself use the official repos for my Haskell packages (and have done so for over a decade), filling in with AUR PKGBUILDs for anything not in the official repos, and sometimes cabal-installing things into $HOME as a temporary solution.

**Comment by simpers** [comment] 2018-02-12 10:11
@LeifW Thanks for the help! I'll have a look at at soon. Been sick and haven't had time.

@IvanMalison Jesus, would you please stop? I get your points, but I am ultimately prioritising in another way than you. For those that want to use those solutions, all the best to them! Including you. But I just don't want to do it that way. I'll consider looking into it later if I like taffybar enough to stick with XMonad to begin with, but I'm most likely going to eventually stop using Haskell based software soon because of other preferences. And that's fine, to each their own.

**Comment by IvanMalison** [comment] 2018-03-25 19:19
@LeifW You should really read that reddit link I posted

https://www.reddit.com/r/archlinux/comments/7hanz7/whats_the_current_state_of_haskell_on_arch/

It's not that its impossible to get things working using arch packages, but it does have the ability to cause breakage because it doesn't respect version number dependencies.

I'm going to close this because we have a package now.

**Closed by IvanMalison** 2018-03-25 19:19 UTC
